// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Niwanna.Data;

#nullable disable

namespace Niwanna.Migrations
{
    [DbContext(typeof(IponContext))]
    [Migration("20260302151824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Niwanna.Models.Ipon", b =>
                {
                    b.Property<int>("IponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IponId");

                    b.ToTable("Ipons");
                });

            modelBuilder.Entity("Niwanna.Models.IponEntry", b =>
                {
                    b.Property<int>("IponEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IponId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IponEntryId");

                    b.HasIndex("IponId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Niwanna.Models.IponEntry", b =>
                {
                    b.HasOne("Niwanna.Models.Ipon", "Ipon")
                        .WithMany("Entries")
                        .HasForeignKey("IponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ipon");
                });

            modelBuilder.Entity("Niwanna.Models.Ipon", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
